### ISSUE TITLE
Window blocks access to corner

### ISSUE THREAD

**Issue by WatermelonsEverywhere** [Liberty-Landing/Liberty-Station-13#119]
This reinforced window blocks access to the tile with the radios.

![image](https://user-images.githubusercontent.com/21104734/233875324-faece7c0-4c85-4c76-b899-3abcd6d95151.png)

**Comment by Dissentbay** [comment]
yeah, not exactly a bug, the window impedes you from interacting with the turf that has the table and the disk due to pathing, it will see the window and say...nah can't reach bro

the actual fix for it is breaking the glass, or coding a new backend pathing for the server...or just unmapping the glasses
