### ISSUE TITLE
Thermoelectric turbine trouble

### ISSUE THREAD

**Issue by SFox63** [Liberty-Landing/Liberty-Station-13#438]
The thermoelectric turbines DO work, but need to be completely rewired every time. Every cable running from the console to the turbines need to be relaid.
![cable](https://github.com/Liberty-Landing/Liberty-Station-13/assets/132799046/0ad76ed6-3737-4f40-9202-c782c915324b)

**Comment by Dissentbay** [comment]
so, it appears the issue is in mapping
it is weird, but follow me through this short rabbit hole
we got "fake" wires
nothing seems wrong with them, bot looking at them or in code
but they refuse to form or join a powernet, which is the problem you're experiencing
right now, the fix for it is to delete the wire in mapping and redo them
I'm not sure if the medical catboy is on it, but it might be work asking him on discord

**Comment by ThePainkiller** [comment]
Hello, "medical catboy" here
The issue was that someone somehow used varedited wires that had the WRONG orientation all the time, according to the graphic on the wires dm file
My latest PR addresses this
![image](https://github.com/Liberty-Landing/Liberty-Station-13/assets/1294508/c6ab30d3-051e-419f-8b48-fcc6d528dc39)
As you can see, all four functional and working and detected roundstart
